# -*- coding: utf-8 -*-
"""remove_noneng.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwwjYu11uvbG03WJa9qDl1U5YYDsWngw
"""

import nltk
nltk.download('words')
from nltk.corpus import words
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
import pandas as pd

df = pd.read_csv("Google.csv", sep = ";")
len(df.index)

df.head(50)

def prep(text):
  lemmatizer = WordNetLemmatizer()
  tokenizer = nltk.tokenize.WhitespaceTokenizer()
  return [lemmatizer.lemmatize(w,"v") for w in tokenizer.tokenize(text)]

df["translation"] = df.translation.apply(prep)

def remove_noneng(sent):
  words = set(nltk.corpus.words.words())
  return " ".join(w for w in sent if w.lower() in words or not w.isalpha())
df["translation"] = df.translation.apply(remove_noneng)  
df.head()

df.head(50)

df.to_csv("processed.csv", sep = ";")